[package]
name = "geodesy"
version = "0.1.0"
authors = ["Thomas Knudsen <knudsen.thomas@gmail.com>"]
edition = "2018"
default-run = "ost"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
yaml-rust = "0.4"
phf = { version = "0.7.24", features = ["macros"] }
