[package]
name = "geodesy"
description = "A platform for experiments with geodetic transformations and data flow"
keywords = ["geodesy", "cartography", "transformations", "geography"]
categories = ["science"]
license = "MIT OR Apache-2.0"
version = "0.7.1"

authors = ["Thomas Knudsen <knudsen.thomas@gmail.com>"]
readme = "README.md"
repository = "https://github.com/busstoptaktik/geodesy/"
edition = "2021"

default-run = "kp"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core functionality
dirs = "3.0"
memmap = "0.7"
enum-iterator = "0.7.0"
uuid = { version = "0.8", features = ["v4"] }

# We're eliminating these
yaml-rust = "0.4"
zip = "0.5"

# Command line program helpers
structopt = "0.3"
exitcode = "1.1"

# Logging and error handling
log = "0.4"
simple_logger = "1.13"
thiserror = "1.0"
anyhow = "1.0"
