[package]
name = "geodesy"
description = "A platform for experiments with geodetic transformations and data flow"
keywords = ["geodesy", "cartography", "transformations", "geography"]
categories = ["science"]
authors = ["Thomas Knudsen <knudsen.thomas@gmail.com>"]
readme = "README.md"
license = "MIT OR Apache-2.0"

version = "0.7.1"
edition = "2021"
default-run = "kp"
repository = "https://github.com/busstoptaktik/geodesy/"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dirs = "3.0"
yaml-rust = "0.4"
zip = "0.5"
structopt = "0.3"
exitcode = "1.1"
log = "0.4"
simple_logger = "1.13"
thiserror = "1.0"
anyhow = "1.0"
