[package]
name = "geodesy"
description = "A platform for experiments with geodetic transformations and data flow"
keywords = ["geodesy", "cartography", "transformations", "geography"]
categories = ["science"]
license = "MIT OR Apache-2.0"
version = "0.7.1"

authors = ["Thomas Knudsen <knudsen.thomas@gmail.com>"]
readme = "README.md"
repository = "https://github.com/busstoptaktik/geodesy/"
edition = "2021"

default-run = "pq"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Core functionality
dirs = "3.0"
# memmap = "0.7"
uuid = { version = "0.8", features = ["v4"] }

# Command line program helpers
clap = { version = "3.1.18", features = ["derive"] }

# Logging and error handling
log = "0.4"
simple_logger = "1.13"
thiserror = "1.0"
anyhow = "1.0"

[dev-dependencies]
# mockall = "0.11.1"
